name: Sugar

vyper:
  evm_version: cancun
  output_format:
    - bytecode
    - abi
    - solc_json

dependencies:
  - site_package: snekmate
    config_override:
      contracts_folder: .

networks:
  custom:
    - name: mainnet
      ecosystem: mode
      chain_id: 34443
    - name: mainnet
      ecosystem: lisk
      chain_id: 1135
    - name: mainnet
      ecosystem: metall2
      chain_id: 1750
    - name: mainnet
      ecosystem: ink
      chain_id: 57073
    - name: mainnet
      ecosystem: soneium
      chain_id: 1868
    - name: mainnet
      ecosystem: superseed
      chain_id: 5330

node:
  mode:
    mainnet:
      uri: https://mode.drpc.org
  lisk:
    mainnet:
      uri: https://lisk.drpc.org
  metall2:
    mainnet:
      uri: https://metall2.drpc.org
  optimism:
    mainnet:
      uri: https://optimism-mainnet.wallet.coinbase.com
  ink:
    mainnet:
      uri: https://ink.drpc.org
  soneium:
    mainnet:
      uri: https://rpc.soneium.org
  superseed:
    mainnet:
      uri: https://mainnet.superseed.xyz
